In [1]:
lvl <- c(8, 10, 10, 1, 10, 10, 8, 12, 1, 12)

In [2]:
sum.ele <- sum(lvl)
avg.ele <- mean(lvl)
med.ele <- median(lvl)
len <- length(lvl)
std.ele <- sd(lvl)
rnd.std.ele <- round(std.ele)
print(rnd.std.ele)
print(paste("The sum is",sum.ele))

[1] 4
[1] "The sum is 82"


In [3]:
draw <- function(){
    deck <- c("Duke","Asssasin","Captain","Ambassodor","contessa")
    sample.deck <- sample(deck,size = 3 , replace = T)
    print(sample.deck)
    
}

draw()

[1] "Ambassodor" "Duke"       "contessa"  


In [4]:
flip <- function(){
    coin <- c("heads","tails")
    toss <- sample(coin,size = 1,prob = c(0.3,0.7))
    print(toss)
}

flip()

[1] "heads"


In [5]:
weight <- c(71, 67, 83, 67)
height <- c(1.75, 1.81, 1.78, 1.82, 1.97, 2.12, 2.75)

In [6]:
BMI <- weight/height

Warning message in weight/height:
“longer object length is not a multiple of shorter object length”


In [7]:
BMI

[1] 40.57143 37.01657 46.62921 36.81319 36.04061 31.60377 30.18182

In [8]:
age <- c(23,4,76,89)

In [9]:
summary(age)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   4.00   18.25   49.50   48.00   79.25   89.00 

In [10]:
attributes(age)

NULL

In [11]:
names(age)

NULL

In [12]:
names(age) <- c("Sahil","Rajat","Champion","Aristotle")

In [13]:
names(age)

[1] "Sahil"     "Rajat"     "Champion"  "Aristotle"

In [14]:
my.vec <- 1:4

In [19]:
a <- c("sahil","nikki",vimal,"manju")

ERROR: Error in eval(expr, envir, enclos): object 'vimal' not found


In [20]:
names(a) <- my.vec

In [21]:
print(a)

      1       2       3       4 
"sahil" "nikki" "vimal" "manju" 


# Vector Exercise

In [25]:
atk <- seq(from = 10 , to = 200 , by = 20)

In [26]:
atk

[1]  10  30  50  70  90 110 130 150 170 190

In [27]:
atk[6]

[1] 110

In [29]:
atk[-c(1:5,7:10)]

[1] 110

In [30]:
atk[-2]

[1]  10  50  70  90 110 130 150 170 190

In [32]:
atk[c(1,3,5,7,9)]

[1]  10  50  90 130 170

In [38]:
#atk[-c(4,5,6)]
atk[-(4:6)]

[1]  10  30  50 130 150 170 190

In [37]:
atk[atk>150]

[1] 170 190

In [40]:
s <- seq(from = 2 ,to = 30 , by = 2)
s

[1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30

In [41]:
attributes(s)

NULL

In [48]:
dim(s) <- c(3,5)

In [49]:
s

[,1] [,2] [,3] [,4] [,5]
[1,] 2     8   14   20   26  
[2,] 4    10   16   22   28  
[3,] 6    12   18   24   30

# Matric Exercise

In [90]:
player <- c(rep("dark",5),rep("light",5))
player

[1] "dark"  "dark"  "dark"  "dark"  "dark"  "light" "light" "light" "light"
[10] "light"

In [91]:
piece <- c("king", "queen", "pawn", "pawn", "knight", "bishop", "king", "rook", "pawn", "pawn")

In [92]:
chess <- c(player,piece)

In [94]:
dim(chess) <- c(10,2)

In [95]:
chess

[,1]  [,2]  
 [1,] dark  king  
 [2,] dark  queen 
 [3,] dark  pawn  
 [4,] dark  pawn  
 [5,] dark  knight
 [6,] light bishop
 [7,] light king  
 [8,] light rook  
 [9,] light pawn  
[10,] light pawn

In [98]:
columns<- c("Player","Peice")

In [99]:
colnames(chess) <- columns

In [100]:
chess

Player Peice 
 [1,] dark   king  
 [2,] dark   queen 
 [3,] dark   pawn  
 [4,] dark   pawn  
 [5,] dark   knight
 [6,] light  bishop
 [7,] light  king  
 [8,] light  rook  
 [9,] light  pawn  
[10,] light  pawn

In [103]:
data <- matrix(chess,nrow = 10,dimnames = list(NULL,c("Player","Peice")))

In [104]:
data

Player Peice 
 [1,] dark   king  
 [2,] dark   queen 
 [3,] dark   pawn  
 [4,] dark   pawn  
 [5,] dark   knight
 [6,] light  bishop
 [7,] light  king  
 [8,] light  rook  
 [9,] light  pawn  
[10,] light  pawn

In [105]:
chess

Player Peice 
 [1,] dark   king  
 [2,] dark   queen 
 [3,] dark   pawn  
 [4,] dark   pawn  
 [5,] dark   knight
 [6,] light  bishop
 [7,] light  king  
 [8,] light  rook  
 [9,] light  pawn  
[10,] light  pawn

In [106]:
if(chess==data){
    print("Yes")
}else{
    print("No")
}

Warning message in if (chess == data) {:
“the condition has length > 1 and only the first element will be used”


[1] "Yes"


In [115]:
new.chess <- t(chess)

In [113]:
Turn <- c(3, 5, 2, 2, 7, 4, 6, 5, 2, 1)

In [120]:
new.chess <- rbind(new.chess,Turn)

In [121]:
chess <- t(new.chess)

In [123]:
chess

Player Peice  Turn
 [1,] dark   king   3   
 [2,] dark   queen  5   
 [3,] dark   pawn   2   
 [4,] dark   pawn   2   
 [5,] dark   knight 7   
 [6,] light  bishop 4   
 [7,] light  king   6   
 [8,] light  rook   5   
 [9,] light  pawn   2   
[10,] light  pawn   1

In [133]:
chess[6,2]

Peice 
"bishop"

In [139]:
chess[,1:2]

Player Peice 
 [1,] dark   king  
 [2,] dark   queen 
 [3,] dark   pawn  
 [4,] dark   pawn  
 [5,] dark   knight
 [6,] light  bishop
 [7,] light  king  
 [8,] light  rook  
 [9,] light  pawn  
[10,] light  pawn

In [140]:
chess[1:5,]

Player Peice  Turn
[1,] dark   king   3   
[2,] dark   queen  5   
[3,] dark   pawn   2   
[4,] dark   pawn   2   
[5,] dark   knight 7

In [148]:
chess[,c("Player","Peice")]

Player Peice 
 [1,] dark   king  
 [2,] dark   queen 
 [3,] dark   pawn  
 [4,] dark   pawn  
 [5,] dark   knight
 [6,] light  bishop
 [7,] light  king  
 [8,] light  rook  
 [9,] light  pawn  
[10,] light  pawn

In [141]:
chess[,-2]

Player Turn
 [1,] dark   3   
 [2,] dark   5   
 [3,] dark   2   
 [4,] dark   2   
 [5,] dark   7   
 [6,] light  4   
 [7,] light  6   
 [8,] light  5   
 [9,] light  2   
[10,] light  1

In [142]:
chess[2,-2]

Player   Turn 
"dark"    "5"

In [146]:
chess[7,3]=3

In [147]:
chess

Player Peice  Turn
 [1,] dark   king   3   
 [2,] dark   queen  5   
 [3,] dark   pawn   2   
 [4,] dark   pawn   2   
 [5,] dark   knight 7   
 [6,] light  bishop 4   
 [7,] light  king   3   
 [8,] light  rook   5   
 [9,] light  pawn   2   
[10,] light  pawn   1

In [149]:
chess[7,3]

Turn 
 "3"

In [153]:
mat.data <- matrix(data = runif(n=12,min=10,max = 40),byrow = TRUE , nrow = 3)

In [154]:
mat.data

[,1]     [,2]     [,3]     [,4]    
[1,] 38.18270 39.08892 38.94444 34.65549
[2,] 22.95148 28.21206 25.88528 15.10765
[3,] 36.82429 21.68851 26.20234 11.62820

In [155]:
columns <- c("uno", "dos", "tres", "cuatro")
rows <- c("x","y","z")

In [156]:
colnames(mat.data) <- columns

In [157]:
rownames(mat.data) <- rows

In [158]:
mat.data

uno      dos      tres     cuatro  
x 38.18270 39.08892 38.94444 34.65549
y 22.95148 28.21206 25.88528 15.10765
z 36.82429 21.68851 26.20234 11.62820

In [159]:
scaled <- mat.data * 10

In [160]:
scaled

uno      dos      tres     cuatro  
x 381.8270 390.8892 389.4444 346.5549
y 229.5148 282.1206 258.8528 151.0765
z 368.2429 216.8851 262.0234 116.2820

In [163]:
new.mat <- matrix(mat.data,nrow = 3,ncol = 3)

In [164]:
new.mat

[,1]     [,2]     [,3]    
[1,] 38.18270 39.08892 38.94444
[2,] 22.95148 28.21206 25.88528
[3,] 36.82429 21.68851 26.20234

In [165]:
m.mat <- new.mat[ , -4]

In [166]:
m.mat

[,1]     [,2]     [,3]    
[1,] 38.18270 39.08892 38.94444
[2,] 22.95148 28.21206 25.88528
[3,] 36.82429 21.68851 26.20234

In [173]:
m1 <- matrix(rnorm(25,mean = 10 , sd =5) , nrow = 5)

In [171]:
m1

[,1]      [,2]      [,3]      [,4]      [,5]     
[1,] 12.342957  9.184174 16.320873 11.349480 11.169639
[2,] 15.935278  3.616956 19.401146  9.893287 13.161123
[3,]  9.675597 16.701028 13.855424 13.133584  6.988940
[4,] 18.619972  9.100036  6.155176 16.289776  6.000969
[5,]  6.432723  8.059221 16.714614  8.824610  8.496039

In [174]:
m2 <- matrix(runif(n = 25 , min = 10 , max = 100), nrow = 5)

In [181]:
col.avg <- colMeans(m1)

In [182]:
col.avg

[1]  9.466250  9.544858 11.962679 10.138080  7.506612

In [180]:
rowMeans(m1)

[1]  7.829257 11.961661 10.583350 10.027632  8.216581

In [183]:
colSums(m1)

[1] 47.33125 47.72429 59.81339 50.69040 37.53306

In [184]:
rowSums(m1)

[1] 39.14629 59.80830 52.91675 50.13816 41.08290

In [185]:
max(m1)
min(m1)

[1] 18.94473

[1] -1.210011

In [186]:
m1

[,1]        [,2]      [,3]      [,4]      [,5]     
[1,]  6.34001566 17.180617 10.466564  6.369100 -1.210011
[2,] 18.94473221  9.290522  8.655145 11.667106 11.250799
[3,] 12.30536707  7.528854 13.657373  6.467631 12.957525
[4,]  9.64649770 10.655199 11.333298  8.727803  9.775361
[5,]  0.09463966  3.069101 15.701014 17.458762  4.759387

In [188]:
max(m1[,-c(1,2,4,5)])

[1] 15.70101

In [189]:
min(m1[,3])

[1] 8.655145

In [190]:
 chess

Player Peice  Turn
 [1,] dark   king   3   
 [2,] dark   queen  5   
 [3,] dark   pawn   2   
 [4,] dark   pawn   2   
 [5,] dark   knight 7   
 [6,] light  bishop 4   
 [7,] light  king   3   
 [8,] light  rook   5   
 [9,] light  pawn   2   
[10,] light  pawn   1

In [193]:
d1 <- chess[,"Peice"]

In [194]:
d1

[1] "king"   "queen"  "pawn"   "pawn"   "knight" "bishop" "king"   "rook"  
 [9] "pawn"   "pawn"

In [201]:
new.d1 <- factor(x = d1 , levels = c("King", "Queen", "Rook", "Bishop", "Knight", "Pawn"),labels = c("K","Q","R","B","K","P"))

In [203]:
levels(new.d1) <- c("K","Q","R","B","K","P")

In [204]:
str(new.d1)

 Factor w/ 5 levels "K","Q","R","B",..: NA NA NA NA NA NA NA NA NA NA


In [205]:
new.d1 <- factor(d1, ordered = TRUE, levels = c("K", "Q", "R", "B", "K", "P"),
                        labels = c("King", "Queen", "Rook", "Bishop", "Knight", "Pawn"))


In [207]:
str(new.d1)

 Ord.factor w/ 6 levels "King"<"Queen"<..: NA NA NA NA NA NA NA NA NA NA


# List Exercise

In [219]:
li <- list(seq(from = 1,to = 10 , by = 2),list("Happy Birthday","Archery"))

In [223]:
li[[2]][[1]]

[1] "Happy Birthday"

In [224]:
li[[2]][[2]]

[1] "Archery"

In [228]:
li[[1]]

[1] 1 3 5 7 9

In [229]:
vec1 <- li[[1]]

In [231]:
typeof(vec1)

[1] "double"

In [232]:
vec2 <- li[[2]][[1]]

In [233]:
vec2

[1] "Happy Birthday"

In [234]:
class(vec2)

[1] "character"

In [263]:
x <- readline(paste("Please insert the data : "))
print(x)

Please insert the data :  12


[1] "12"


In [264]:
if(x>1 & x<65){
    print("Rotten")
}else if(x>66 & x<75){
    print("fresh")
}else if(x>76 & x<100){
    print("Correct")
}

[1] "Rotten"


In [2]:
sum <- 0
for (vals in 1:5){
     sum <- sum+vals
}
print(sum)

[1] 15
